apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.serviceName }}
  labels:
    app: {{ .Values.backend.serviceName }}
spec:
  ports:
    - port: {{ .Values.backend.containers.port }}
      protocol: TCP
      targetPort: {{ .Values.backend.containers.port }}
  selector:
    app: {{ .Values.backend.label }}