version: '3.8'

services:
  backend:
    container_name: momo-store-backend
    image: ${CI_REGISTRY_IMAGE}/momo-store-backend:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    expose:
      - "8081"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://backend:8081/api/health"]
    #   interval: 1m
    #   timeout: 3s
    #   retries: 5
    #   start_period: 2m
    networks:
      - momo-network
  
  frontend:
    container_name: momo-store-frontend
    image: ${CI_REGISTRY_IMAGE}/momo-store-frontend:latest
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    networks:
      - momo-network

networks:
  momo-network:
    driver: bridge